---
title: "EDA"
author: "Paulo Magalang"
date: "5/2/2021"
output: html_document
---

```{r setup, message = FALSE}
# loading in relevant libraries
library(tidyverse)
library(Rtsne)
library(ggthemes)
```

```{r data_prep}
# load in data
data <- read_csv("../data/features_30_sec.csv")

# take a look
head(data)
dim(data)

# 1000 samples for 58 features (first column is the file name and 60th col is label)

# getting some summary stats
#summary(data)

# questions to consider:
# What are the units of length (ms?)

# drop filename, clip length, and label columns, convert to a matrix
filtered_data <- data[ ,-c(1, 2, 60)] %>%
  as.data.frame() %>%
  data.matrix()
```

```{r pca}
# take the first 20 PCs
pca <- prcomp(filtered_data, center = TRUE, scale. = TRUE, rank. = 20)

# create barplot to determine percent variance explained
pcvar <- pca$sdev^2
pcvar.pct <- tibble(pctvar = pcvar / sum(pcvar) * 100,
                    PC = 1:length(pcvar))

pcvar.pct[1:20, ] %>% ggplot(aes(x = PC, y = pctvar)) + geom_col() +
  ggtitle("Percent Variance Explained")

# seems like PCs 1-3 (maybe even 4?) explain the variance in the data well enough

# some extra data wrangling

# add info about files to make joining easier
PCs <- as_tibble(pca$x) %>%
  mutate(filename = data$filename)

# join the original data with PC data
all_data <- left_join(data, PCs, by = "filename")
```

```{r pca_data_vis}
# plot PCs
label_PC2vsPC1 <- all_data %>% ggplot(aes(x = PC2, y = PC1, color = `label`)) + geom_point() +
  scale_color_calc()

label_PC2vsPC1

label_PC3vsPC1 <- all_data %>% ggplot(aes(x = PC3, y = PC1, color = `label`)) + geom_point() +
  scale_color_calc()

label_PC3vsPC1

label_PC2vsPC3 <- all_data %>% ggplot(aes(x = PC3, y = PC2, color = `label`)) + geom_point() +
  scale_color_calc()

label_PC2vsPC3
```



```{r tsne}
# perform tSNE
tsne <- Rtsne(filtered_data, dims = 2, perplexity = 30, check_duplicates = FALSE, verbose = TRUE, max_iter = 3000)

tsne_df <- tsne$Y %>% as.data.frame()

# add label info to dataframe
tsne_df$label <- data$label

tsne_df %>% ggplot(aes(x = V1, y = V2, color = `label`)) + geom_point() +
  scale_color_calc()
```







